# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jro/DEV/CV2C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jro/DEV/CV2C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jro/DEV/CV2C/CMakeFiles /home/jro/DEV/CV2C//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jro/DEV/CV2C/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cv2c

# Build rule for target.
cv2c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cv2c
.PHONY : cv2c

# fast build rule for target.
cv2c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/build
.PHONY : cv2c/fast

#=============================================================================
# Target rules for targets named creertables

# Build rule for target.
creertables: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 creertables
.PHONY : creertables

# fast build rule for target.
creertables/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/creertables.dir/build.make CMakeFiles/creertables.dir/build
.PHONY : creertables/fast

#=============================================================================
# Target rules for targets named sqltest

# Build rule for target.
sqltest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sqltest
.PHONY : sqltest

# fast build rule for target.
sqltest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqltest.dir/build.make CMakeFiles/sqltest.dir/build
.PHONY : sqltest/fast

#=============================================================================
# Target rules for targets named affichePlis

# Build rule for target.
affichePlis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 affichePlis
.PHONY : affichePlis

# fast build rule for target.
affichePlis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/affichePlis.dir/build.make CMakeFiles/affichePlis.dir/build
.PHONY : affichePlis/fast

affichePlis.o: affichePlis.cpp.o
.PHONY : affichePlis.o

# target to build an object file
affichePlis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/affichePlis.dir/build.make CMakeFiles/affichePlis.dir/affichePlis.cpp.o
.PHONY : affichePlis.cpp.o

affichePlis.i: affichePlis.cpp.i
.PHONY : affichePlis.i

# target to preprocess a source file
affichePlis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/affichePlis.dir/build.make CMakeFiles/affichePlis.dir/affichePlis.cpp.i
.PHONY : affichePlis.cpp.i

affichePlis.s: affichePlis.cpp.s
.PHONY : affichePlis.s

# target to generate assembly for a file
affichePlis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/affichePlis.dir/build.make CMakeFiles/affichePlis.dir/affichePlis.cpp.s
.PHONY : affichePlis.cpp.s

creertables.o: creertables.cpp.o
.PHONY : creertables.o

# target to build an object file
creertables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/creertables.dir/build.make CMakeFiles/creertables.dir/creertables.cpp.o
.PHONY : creertables.cpp.o

creertables.i: creertables.cpp.i
.PHONY : creertables.i

# target to preprocess a source file
creertables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/creertables.dir/build.make CMakeFiles/creertables.dir/creertables.cpp.i
.PHONY : creertables.cpp.i

creertables.s: creertables.cpp.s
.PHONY : creertables.s

# target to generate assembly for a file
creertables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/creertables.dir/build.make CMakeFiles/creertables.dir/creertables.cpp.s
.PHONY : creertables.cpp.s

cv2c.o: cv2c.cpp.o
.PHONY : cv2c.o

# target to build an object file
cv2c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/cv2c.cpp.o
.PHONY : cv2c.cpp.o

cv2c.i: cv2c.cpp.i
.PHONY : cv2c.i

# target to preprocess a source file
cv2c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/cv2c.cpp.i
.PHONY : cv2c.cpp.i

cv2c.s: cv2c.cpp.s
.PHONY : cv2c.s

# target to generate assembly for a file
cv2c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/cv2c.cpp.s
.PHONY : cv2c.cpp.s

lireConfig.o: lireConfig.cpp.o
.PHONY : lireConfig.o

# target to build an object file
lireConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/lireConfig.cpp.o
.PHONY : lireConfig.cpp.o

lireConfig.i: lireConfig.cpp.i
.PHONY : lireConfig.i

# target to preprocess a source file
lireConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/lireConfig.cpp.i
.PHONY : lireConfig.cpp.i

lireConfig.s: lireConfig.cpp.s
.PHONY : lireConfig.s

# target to generate assembly for a file
lireConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/lireConfig.cpp.s
.PHONY : lireConfig.cpp.s

outils.o: outils.cpp.o
.PHONY : outils.o

# target to build an object file
outils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/outils.cpp.o
.PHONY : outils.cpp.o

outils.i: outils.cpp.i
.PHONY : outils.i

# target to preprocess a source file
outils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/outils.cpp.i
.PHONY : outils.cpp.i

outils.s: outils.cpp.s
.PHONY : outils.s

# target to generate assembly for a file
outils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/outils.cpp.s
.PHONY : outils.cpp.s

pyOcr.o: pyOcr.cpp.o
.PHONY : pyOcr.o

# target to build an object file
pyOcr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/pyOcr.cpp.o
.PHONY : pyOcr.cpp.o

pyOcr.i: pyOcr.cpp.i
.PHONY : pyOcr.i

# target to preprocess a source file
pyOcr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/pyOcr.cpp.i
.PHONY : pyOcr.cpp.i

pyOcr.s: pyOcr.cpp.s
.PHONY : pyOcr.s

# target to generate assembly for a file
pyOcr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/pyOcr.cpp.s
.PHONY : pyOcr.cpp.s

setconfig.o: setconfig.cpp.o
.PHONY : setconfig.o

# target to build an object file
setconfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/setconfig.cpp.o
.PHONY : setconfig.cpp.o

setconfig.i: setconfig.cpp.i
.PHONY : setconfig.i

# target to preprocess a source file
setconfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/setconfig.cpp.i
.PHONY : setconfig.cpp.i

setconfig.s: setconfig.cpp.s
.PHONY : setconfig.s

# target to generate assembly for a file
setconfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/setconfig.cpp.s
.PHONY : setconfig.cpp.s

sqltest.o: sqltest.cpp.o
.PHONY : sqltest.o

# target to build an object file
sqltest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqltest.dir/build.make CMakeFiles/sqltest.dir/sqltest.cpp.o
.PHONY : sqltest.cpp.o

sqltest.i: sqltest.cpp.i
.PHONY : sqltest.i

# target to preprocess a source file
sqltest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqltest.dir/build.make CMakeFiles/sqltest.dir/sqltest.cpp.i
.PHONY : sqltest.cpp.i

sqltest.s: sqltest.cpp.s
.PHONY : sqltest.s

# target to generate assembly for a file
sqltest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqltest.dir/build.make CMakeFiles/sqltest.dir/sqltest.cpp.s
.PHONY : sqltest.cpp.s

traiterCoin.o: traiterCoin.cpp.o
.PHONY : traiterCoin.o

# target to build an object file
traiterCoin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/traiterCoin.cpp.o
.PHONY : traiterCoin.cpp.o

traiterCoin.i: traiterCoin.cpp.i
.PHONY : traiterCoin.i

# target to preprocess a source file
traiterCoin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/traiterCoin.cpp.i
.PHONY : traiterCoin.cpp.i

traiterCoin.s: traiterCoin.cpp.s
.PHONY : traiterCoin.s

# target to generate assembly for a file
traiterCoin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv2c.dir/build.make CMakeFiles/cv2c.dir/traiterCoin.cpp.s
.PHONY : traiterCoin.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... affichePlis"
	@echo "... creertables"
	@echo "... cv2c"
	@echo "... sqltest"
	@echo "... affichePlis.o"
	@echo "... affichePlis.i"
	@echo "... affichePlis.s"
	@echo "... creertables.o"
	@echo "... creertables.i"
	@echo "... creertables.s"
	@echo "... cv2c.o"
	@echo "... cv2c.i"
	@echo "... cv2c.s"
	@echo "... lireConfig.o"
	@echo "... lireConfig.i"
	@echo "... lireConfig.s"
	@echo "... outils.o"
	@echo "... outils.i"
	@echo "... outils.s"
	@echo "... pyOcr.o"
	@echo "... pyOcr.i"
	@echo "... pyOcr.s"
	@echo "... setconfig.o"
	@echo "... setconfig.i"
	@echo "... setconfig.s"
	@echo "... sqltest.o"
	@echo "... sqltest.i"
	@echo "... sqltest.s"
	@echo "... traiterCoin.o"
	@echo "... traiterCoin.i"
	@echo "... traiterCoin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

